"""Add quantity and category to product

Revision ID: dc1d5054f99b
Revises: 79d0d83375c3
Create Date: 2024-12-02 16:54:53.219514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc1d5054f99b"
down_revision: Union[str, None] = "79d0d83375c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categories_description"), "categories", ["description"], unique=False
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.add_column("products", sa.Column("quantity", sa.Integer(), nullable=False))
    op.add_column("products", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_products_quantity"), "products", ["quantity"], unique=False
    )
    op.create_foreign_key(None, "products", "categories", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_index(op.f("ix_products_quantity"), table_name="products")
    op.drop_column("products", "category_id")
    op.drop_column("products", "quantity")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_description"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
